abundance_data:
  All_species: "../../../data/output/abundance/abundance_all_species.parquet"
  Kingdom: "../../../data/output/abundance/abundance_kingdom.parquet"
  Phylum: "../../../data/output/abundance/abundance_phylum.parquet"
  Class: "../../../data/output/abundance/abundance_class.parquet"
  Order: "../../../data/output/abundance/abundance_order.parquet"
  Family: "../../../data/output/abundance/abundance_family.parquet"

taxonomic_resolution: Kingdom  # [All_species, Kingdom, Phylum, Class, Order, Family]

group_vars:
  All_species: [SS, SSB, SSBS]
  Kingdom: [SS, SSB, SSBS, Kingdom]
  Phylum: [SS, SSB, SSBS, Kingdom, Phylum]
  Class: [SS, SSB, SSBS, Kingdom, Phylum, Class]
  Order: [SS, SSB, SSBS, Kingdom, Phylum, Class, Order]
  Family: [SS, SSB, SSBS, Kingdom, Phylum, Class, Order, Family]

scope:
  geographic:
    Biome:
      - Tropical & Subtropical Moist Broadleaf Forests
      - Tropical & Subtropical Dry Broadleaf Forests
      - Tropical & Subtropical Coniferous Forests
    UN_region: [Americas, Asia, Europe, Oceania, Africa]  # Americas, Asia, Europe, Oceania, Africa
  species:
    All_species: []
    Kingdom:
      - Animalia
      - Plantae
      - Fungi
    Phylum: []
    Class: []
    Order: []
    Family: []

sampler_settings:
  draws: 100
  tune: 100
  cores: 4
  chains: 4
  target_accept: 0.99
  nuts_sampler: "numpyro"

selected_model: bii_ref_model

model_1:
  model_spec: abund_normal
  pymc_key_var_names: [mu_beta, sigma_beta, beta]
  response_var: Max_scaled_abundance
  categorical_vars:
    - Young secondary vegetation
    - Intermediate secondary vegetation
    - Mature secondary vegetation
    - Secondary vegetation (indeterminate age)
    - Plantation forest
    - Pasture
    - Cropland
    - Urban
  continuous_vars:
    - Road_density_10km
    - Pop_density_10km
  study_control_vars:
    - Mean_road_density_10km
    - Mean_pop_density_10km
  response_var_transform: None  # [adjust, square-root, logit, None]


bii_ref_model:
  model_spec: bii_abund_baseline
  pymc_key_var_names: [mu_beta, sigma_beta, beta]
  response_var: Max_scaled_abundance
  categorical_vars:
    - Primary vegetation_Light use
    - Primary vegetation_Intense use
    - Secondary vegetation_Minimal use
    - Secondary vegetation_Light use
    - Secondary vegetation_Intense use
    - Cropland_Minimal use
    - Cropland_Light_Intense
    - Pasture_Minimal use
    - Pasture_Light_Intense
    - Urban_All uses
  continuous_vars:
    - Pop_density_1km_log
    - Road_density_50km_cbrt
    - Mean_pop_density_1km_log
  interaction_terms:
    - Pop_density_1km_log
    - Road_density_50km_cbrt
  study_control_vars: []
  response_var_transform: sqrt  # [adjust, sqrt, logit, null]
